name: AuctionHouse
version: '1.0-SNAPSHOT'
main: com.moontegro.auctionhouse.AuctionHouse
api-version: '1.21'
authors: [ Moontegro ]
description: AuctionHouse plugin
website: https://moontegro.com
commands:
  auctionhouse:
  trade: